_format_version: '3.0'
_transform: true

services:
  # - name: users
  #   # url: http://host.docker.internal:3333
  #   url: ${USERS_SERVICE_URL}
  #   protocol: http
  #   host: host.docker.internal
  #   port: 3333
  #   path: /
  #   routes:
  #     - name: api-users
  #       protocols:
  #         - http
  #         - https
  #       paths:
  #         - /users

  - name: streamings
    # url: http://host.docker.internal:3334
    url: ${STREAMINGS_SERVICE_URL}
    protocol: http
    host: host.docker.internal
    port: 3334
    path: /
    routes:
      - name: api-streamings
        protocols:
          - http
          - https
        paths:
          - /streamings

plugins:
  - name: cors
    config:
      origins:
        - '*'
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Content-Type
        - Authorization
